### ISSUE TITLE
Unable to create a AsyncFuture::Deferred<QList<T>>

### ISSUE THREAD

**Issue by CJYate** [vpicaver/asyncfuture#2]
See:
https://github.com/benlau/asyncfuture/issues/23

Until Qt6 the workaround was to use QVector<T> instead. This no longer works as QVector<T> aliases to QList.

**Comment by vpicaver** [comment]
This has been pushed to the dev branch. Can you confirm that it works for you? I've updated the testcases to detect this issue for QList and QVector. Works for both Qt5 and Qt6.

**Comment by vpicaver** [comment]
https://github.com/vpicaver/asyncfuture/commit/900e4a24e04ebe4894f2ac860c2b4ee7b9f7140a

**Comment by vpicaver** [comment]
This builds under MSVC and g++ with windows and linux for both Qt5 and Qt6. I've push it to the master. Let me know if it doesn't work for you.

**Comment by vpicaver** [comment]
I'm closing this issue, reopen it if it does not work on the master.
