### ISSUE TITLE
observe() no longer works with the QProcess::finished signal after upgrade to Qt6

### ISSUE THREAD

**Issue by nikkiwritescode** [vpicaver/asyncfuture#4]
The `QProcess::finished` signal (https://doc.qt.io/qt-6/qprocess.html#finished) now returns `QProcess::ExitStatus exitStatus` in addition to `int exitCode`. However, when trying to use this with the latest version of AsyncFuture, the following errors are thrown:

```
error: no matching function for call to 'observe(QProcess*&, void(QProcess::*)(int, QProcess::ExitStatus))'
```

This is the code. The only thing I've added is the second parameter to both places as the compiler will not let you just ignore the `exitStatus` parameter:
```
return AsyncFuture::observe(proc, QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished))
        .subscribe([=](int code, QProcess::ExitStatus status) {
            if (code != 0) {
                delete proc;
                throw Exception(QString("Process '%1' returned nonzero exit code %2").arg(program).arg(code));
            }
            if (deleteProcAfterSuccess) delete proc;
        }).future();
```

Please let me know if there is a better way to go about this, but I've spent hours trying to get this to work at this point so I'm out of ideas.

**Comment by vpicaver** [comment]
I've update the documentation on showing you how to support signal with multiple args. Here's what you want to do:

```
auto proc = QSharedPointer<QProcess>(new QProcess());

struct Finished {
    int exitCode = -1;
    QProcess::ExitStatus status = QProcess::CrashExit;
};

auto deferred = AsyncFuture::deferred<Finished>();
QObject::connect(proc.get(), QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished),
                 [&](int code, QProcess::ExitStatus status) {
    //Signal that the deferred is done
    deferred.complete({code, status});
});

proc->start(QString("ls"), QStringList());
```

If this doesn't help, reopen this bug.

**Comment by nikkiwritescode** [comment]
Sadly, this doesn't seem to be working for my use case. It seems the codebase I've inherited was written to use some really old syntax, as the version of the `finished` signal that was in use here [was listed as obsolete even in the 5.15 LTS docs](https://doc.qt.io/qt-5/qprocess-obsolete.html#finished-1). So that's why the issue is arising now -- that obsolete signal was removed entirely in Qt 6.

I've been playing around with the new syntax you provided, and it's certainly closer. I can get my code to compile, and I can generate a QFuture from `deferred.subscribe([=] {}).future()`, but the app crashes upon use. Upon further investigation, the new QFuture doesn't seem to be connected to or know anything about the original process that was passed into the function. I am admittedly still learning how these objects work, so something about my understanding might not be totally accurate. 

To give you an overview of the way I'm trying to use the code example from the original post, the QProcess is being started, then it's being passed into my `observeProcess` function, which passes that QProcess into `AsyncFuture::observe`, and returns the value from that call's chained `future()`. In some cases this returns data, but in other cases it doesn't. But the QFuture created from `deferred` is always empty, no matter what.

Do you know how I can go about populating that QFuture, or generating it in a way that knows about the original QProcess? If not, would it be a huge lift to add a new overload of `observe()` which handles the second parameter of [QProcess::finished](https://doc.qt.io/qt-6/qprocess.html#finished)? Or is my best option here just to rewrite the code in a more standard way?

The full function, as it worked in Qt 5.15, is as follows:
```c++
static QFuture<void> observeProcess(QProcess *proc, bool deleteProcAfterSuccess = true) {
    auto program = proc->program();
    if (proc->error() == QProcess::FailedToStart) {
        delete proc;
        auto def = AsyncFuture::deferred<void>();
        def.complete();
        return def.subscribe([=] { throw Exception(QString("Process '%1' failed to start").arg(program)); }).future();
    }
    AsyncFuture::observe(proc, &QProcess::readyReadStandardError).subscribe([=]() {
        qWarning() << proc->readAllStandardError();
    });
    return AsyncFuture::observe(proc, QOverload<int>::of(&QProcess::finished))
            .subscribe([=](int code) {
        if (code != 0) {
            delete proc;
            throw Exception(QString("Process '%1' returned nonzero exit code %2").arg(program).arg(code));
        }
        if (deleteProcAfterSuccess) delete proc;
    }).future();
}
```
Thank you for your help with this.

Edit: I don't seem to have permission to re-open this Issue.

**Comment by vpicaver** [comment]
I would suggest observing the process before you start the process. It's possible for the QProcess to exit before you have a chance to observe it.

**Do you know what the stack is for the crash?**

I tend not to through exception in async code because of threading. I'm assuming this all executes on the main thread? If not, you might want to use context() instead of subscribe to make sure things are executed on the right thread. 

 ```   
 if (proc->error() == QProcess::FailedToStart) {
        delete proc;
        auto def = AsyncFuture::deferred<void>();
        def.complete();
        return def.subscribe([=] { throw Exception(QString("Process '%1' failed to start").arg(program)); }).future();
    }
```
This code is a bit silly. It should just be:
```
if (proc->error() == QProcess::FailedToStart) {
  throw Exception(QString("Process '%1' failed to start").arg(program));
}
```

This will execute immediately every time, and throw an exception. You don't need to return anything if you're throwing an exception. 
```
auto def = AsyncFuture::deferred<void>();
        def.complete();
        return def.subscribe([=] { throw Exception(QString("Process '%1' failed to start").arg(program)); }).future();
```

**Comment by nikkiwritescode** [comment]
I'm not sure what you mean about using context() instead of subscribe(), as neither the `Deferred` objects nor `AsyncFuture::observe` have such a call. 

I will simplify and refactor this code as you've suggested because I agree with you -- some of this code is silly. I get the idea that the author I'm inheriting this from may not have understood this library super well either, so I'm hoping to find a better way to implement this. But, I can confirm the process is not crashing before this point as `proc->waitForFinished()` waits before crashing, and the resulting files from that process _do_ exist on disk. The job is running successfully behind the scenes in what is supposed to be an asynchronous manner, but I have no way to return data back to the program now that I cannot use AsyncFuture to observe QProcesses directly anymore. That extra step of creating the QFuture from the Deferred object rather than from the QProcess itself seems to strip away any knowledge or reference of that QProcess, leaving code that is trying to reference it to crash. Does that make sense?

**Comment by vpicaver** [comment]
Look in the documentation for:
Observable<R> Observable<T>::context(QObject* contextObject, Completed onCompleted, Cancel onCanceled)

context is the same a subscribe, but it take a contextObject. onCompleted lambda will run in the same thread context as contextObject->thread(). Assuming that thread has an event loop running on it.

Here's the test case / example that should solve you issue of using asyncfuture with QProcess. This shows you how you can get data from the QProcesses's finished signal and print it out. await() is a function that only exists in the testcase btw.

```
    auto proc = QSharedPointer<QProcess>(new QProcess());

    struct Finished {
        int exitCode = -1;
        QProcess::ExitStatus status = QProcess::CrashExit;
    };

    auto deferred = AsyncFuture::deferred<Finished>();
    QObject::connect(proc.get(), QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished),
                     [&](int code, QProcess::ExitStatus status) {
        deferred.complete({code, status});
    });

    proc->start(QString("ls"), QStringList());

    bool subscribeCalled = false;
    deferred.subscribe([&subscribeCalled](Finished finished) {
        qDebug() << "Finished data:" << finished.exitCode << finished.status;
        subscribeCalled = true;
    });

    await(deferred.future(), 100);

    QVERIFY(deferred.future().result().exitCode == proc->exitCode());
    QVERIFY(deferred.future().result().status == proc->exitStatus());
    QVERIFY(subscribeCalled == true);
```

**Comment by vpicaver** [comment]
Since you're on Qt6 you could use Qt6 QFuture signal handling:
https://doc.qt.io/qt-6/qtfuture.html#connect

So instead of the observe you can you 
```
using Args = std::tuple<int, double, QString>;
QFuture<Args> tupleFuture = QtFuture::connect(&object, &Object::multipleArgs)
```
The you can do 
```
tupleFuture.subscribe([](Args args) {
...
});
```

**Comment by vpicaver** [comment]
Are you still having issues with this?

**Comment by nikkiwritescode** [comment]
Yes I am. I apologize for going dark for the past week, as I've not yet been able to spend as much time with it as I would have liked to before reporting back. I've made a _little bit_ of progress with the method of creating a `deferred` object and returning its future, but it's being weird. For the following code snippet, which is simply returning a `QFuture<void>` object to be `await()`ed later:
```cpp
auto deferred = AsyncFuture::deferred<void>();
QObject::connect(proc, QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished), [&](int code, QProcess::ExitStatus status) {
    if(code != 0){
        throw Exception(QString("Process '%1' returned nonzero exit code %2").arg(program).arg(code));
    }
    deferred.complete();
});

proc->start();

bool subscribeCalled = false;
deferred.subscribe([&subscribeCalled]() {
    subscribeCalled = true;
});

return deferred.future();
 ```
...I'm finding that it's just crashing immediately unless I put `proc->waitForFinished();` right after `proc->start();`, and even then it's only working for some things before crashing later. And even if this fully worked, this is freezing the UI and turning it back into a synchronous process so...I feel like something is very wrong if I'm even having to do this.
 
 I don't fully understand why the old method of
 ```cpp
 return AsyncFuture::observe(proc, QOverload<int>::of(&QProcess::finished)).subscribe([=](int code) {
     if (code != 0) {
         throw Exception(QString("Process '%1' returned nonzero exit code %2").arg(program).arg(code));
     }
}).future();
```
...works fine, but `return deferred.future();` as shown in the example is crashing. The code I'm trying to get up to speed on is actually open source, so I can link you to the actual code if it would help to diagnose this. 

As it stands in the repository, the project is still on Qt5. But this all arose when trying to upgrading the project to Qt6. I've been able to tweak everything else, and this is now the only line in the entire codebase standing in the way: https://github.com/FortuneStreetModding/csmm-qt/blob/main/lib/exewrapper.cpp#L59

The `<int>` version of `QProcess::finished` was depreciated even in 5.15, in favor of the current `<int, QProcess::ExitStatus>` version, so this breaks in Qt6 since the `<int>` version was removed entirely. And asyncfuture doesn't support that additional argument, so rock, meet hard place. This is why I showed up asking for support for that second parameter.

At this point, I've stashed my Qt6 branch and have gone back to Qt5, since the double parameter version of `QProcess::finished` existed back then too. I want to reduce as many variables as possible so I can hone in on reworking this part specifically to remove references to depreciated items. So for the examples above, this is Qt5. Then, once I'm able to get the reworked version functioning, I'll fit the fix into that branch.

In the meantime, do you have any insight as to what might be different between these two QFutures? Why does one work perfectly but the other only partially work?

**Comment by vpicaver** [comment]
You've stumbled upon a classic issue with asynchronous programming in C++. The problem with subscribeCalled is that it's stack-allocated. When you pass a reference to this local variable into a lambda and then return from the function, the subscribeCalled variable goes out of scope, and its memory could be reclaimed. Accessing it later in the callback leads to undefined behavior, which is likely causing the crash.

A safer approach is to allocate subscribeCalled on the heap. You could use a std::shared_ptr<bool> to ensure that the memory stays valid for the lifetime of the callback. Here’s a quick example:

```
auto subscribeCalled = std::make_shared<bool>(false);
deferred.subscribe([subscribeCalled]() {
    *subscribeCalled = true;
});
```

Regarding your transition to Qt6 and the issues with QProcess::finished and AsyncFuture, it's indeed a tricky situation. I would use QFuture<Args> workaround. It allows for handling multiple arguments in your connect statement, which aligns with the new signal for QProcess::finished in Qt6. Something like this might work:

```
using Args = std::tuple<int, QProcess::ExitStatus>;
QFuture<Args> tupleFuture = QtFuture::connect(proc, &QProcess::finished);
```

This is how I would implement observeProcess for Qt6:
```
static QFuture<void> observeProcess(QProcess *proc, bool deleteProcAfterSuccess = true) {
    auto program = proc->program();
    if (proc->error() == QProcess::FailedToStart) {
        proc->deleteLater();
        throw Exception(QString("Process '%1' failed to start").arg(program));
    }

    QObject::connect(proc, &QProcess::readyReadStandardError, [proc]() {
        qWarning() << proc->readAllStandardError();
    });
    
    using Args = std::tuple<int, QProcess::ExitStatus>;
    QFuture<Args> future = QtFuture::connect(proc, &QProcess::finished);
    return AsyncFuture::observe(tuple)
            .subscribe([=](int code, QProcess::ExitStatus status) {
        if (code != 0) {
            proc->deleteLater();
            throw Exception(QString("Process '%1' returned nonzero exit code %2").arg(program).arg(code));
        }
        if (deleteProcAfterSuccess) proc->deleteLater();
    }).future();
}
```

I haven't tested the code above, but it should get you going in the correct direction.

**Comment by nikkiwritescode** [comment]
Oh! Allocating `subscribeCalled` on the heap worked! This has allowed me to get it working at a base level without the depreciated signal, so I was able to apply this to my Qt6 branch and get it minimally working. Thank you! I'm still having to have `proc->waitForFinished()` for some reason, so it's not perfect, but this is great progress.

Now that I'm over in Qt6 land, and it's working at a base level, I'm ready to start migrating to the new QFuture syntax. This part seems to work fine:
```cpp
using Args = std::tuple<int, QProcess::ExitStatus>;
QFuture<Args> future = QtFuture::connect(proc, &QProcess::finished);
```
... but it looks like AsyncFuture doesn't support it? The error I'm seeing on the next line is as follows:

`.../lib/asyncfuture.h:21:52: error: static assertion failed: subscribe(callback): Callback function should not take more than 1 argument`

The full error is really long, but it goes on to mention `ASYNCFUTURE_ERROR_CALLBACK_NO_MORE_ONE_ARGUMENT`. So this seems to be specifically disallowed? The line it's erroring on is that callback function:
```cpp
using Args = std::tuple<int, QProcess::ExitStatus>;
QFuture<Args> future = QtFuture::connect(proc, &QProcess::finished);
return AsyncFuture::observe(future)
            .subscribe([=](int code, QProcess::ExitStatus status) <--- this line
```
...and if I remove `QProcess::ExitStatus status` I end up with a mismatch error.

I think we're getting really close! Thank you so much for taking the time to help, I really appreciate it.

**Comment by vpicaver** [comment]
You are correct, the code above does have a syntax error. Here's an update version that should work:
```
static QFuture<void> observeProcess(QProcess *proc, bool deleteProcAfterSuccess = true) {
    auto program = proc->program();
    if (proc->error() == QProcess::FailedToStart) {
        proc->deleteLater();
        throw Exception(QString("Process '%1' failed to start").arg(program));
    }

    QObject::connect(proc, &QProcess::readyReadStandardError, [proc]() {
        qWarning() << proc->readAllStandardError();
    });
    
    using Args = std::tuple<int, QProcess::ExitStatus>;
    QFuture<Args> future = QtFuture::connect(proc, &QProcess::finished);
    return AsyncFuture::observe(future)
        .subscribe([=](Args args) {
            const auto code = std::get<0>(args);
            const auto status = std::get<1>(args);
            if (code != 0) {
                proc->deleteLater();
                throw Exception(QString("Process '%1' returned nonzero exit code %2").arg(program).arg(code));
            }
            if (deleteProcAfterSuccess) proc->deleteLater();
    }).future();
}

**Comment by nikkiwritescode** [comment]
This latest version works perfectly! Thank you so much for all your help!
